baseurl         = "https://wkcheung.github.io/"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Amets Cheung | Software Engineer"
  subtitle    = "Software Engineer | Traveller | Movie Lover"
  copyright   = "© 2018"

  cover       = "img/_blog-cover.jpg"
  description = "A personal site dedicated to share the thoughts of Amets Wing Kei Cheung"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = "wkc124"
  githubName = "wkcheung"
  linkedinName = "amets-wkcheung"
  mediumName = ""

  logo = "logo.png"
  orgName = "Amets Wing Kei Cheung"
  orgWebsite = "https://wkcheung.github.io"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "EM"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Blog"
  url = "/categories/"
  weight = 99
